### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by ngmartins** [chemelli74/Shelly-utils#1]
Hey there, thanks for sharing this seems to be exactly what I have been looking for.
Can you please write some notes on the readme file about how to use this? I am new on HA. I can extrapolate What should I use in the what .yaml file. But I don't know what to do with the files outside the **homeassistant** folder.

I am using a Raspberry pi to run HA.

Thanks in advance :)

**Comment by chemelli74** [comment]
@ngmartins, sorry for a so late feedback. Didn't get the time to maintain the script in this repository.

Simone
